
/*
CREATING ROLES AND ASSIGNING THE REQUIRED PRIVILIGES
*/
set serveroutput on;
DECLARE
   v_count INTEGER;
BEGIN
   SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'PASSENGERUSER';
   IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER PassengerUser IDENTIFIED BY WorldWideTraveller2024';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO PassengerUser';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON PASSENGER_ONBOARDING_PKG TO PASSENGERUSER';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON PASSENGER_UPDATING_PKG TO PASSENGERUSER';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON PASSENGER_DELETE_PKG TO PASSENGERUSER';        
        DBMS_OUTPUT.PUT_LINE('User PASSENGER CREATED and assigned the necessary priviliges SUCCESSFULLY');
   ELSE
        DBMS_OUTPUT.PUT_LINE('User already exists');
   END IF;
END;
/


DECLARE
   v_count INTEGER;
BEGIN
   SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'ACCOUNTANT';
   IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER ACCOUNTANT IDENTIFIED BY BookKeepingMoneyMan2024';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ACCOUNTANT';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON acct_pkg TO ACCOUNTANT';     
        EXECUTE IMMEDIATE 'GRANT SELECT ON  BAGGAGE TO ACCOUNTANT';     
        EXECUTE IMMEDIATE 'GRANT SELECT ON  ORDERS TO ACCOUNTANT';
        EXECUTE IMMEDIATE 'GRANT SELECT ON  FLIGHT TO ACCOUNTANT';
        EXECUTE IMMEDIATE 'GRANT SELECT ON  TICKET TO ACCOUNTANT';
        EXECUTE IMMEDIATE 'GRANT SELECT ON  AIRLINES TO ACCOUNTANT'; 
        EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO ACCOUNTANT';
        DBMS_OUTPUT.PUT_LINE('User ACCOUNTANT CREATED and assigned the necessary priviliges');
   ELSE
        DBMS_OUTPUT.PUT_LINE('User already exists');
   END IF;
END;
/



DECLARE
   v_count INTEGER;
BEGIN
   SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'ANALYST';
   IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER ANALYST IDENTIFIED BY BigDataScientist2024';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ANALYST';
        EXECUTE IMMEDIATE 'GRANT SELECT ON  BAGGAGE TO ANALYST';     
        EXECUTE IMMEDIATE 'GRANT SELECT ON  ORDERS TO ANALYST';
        EXECUTE IMMEDIATE 'GRANT SELECT ON  FLIGHT TO ANALYST';
        EXECUTE IMMEDIATE 'GRANT SELECT ON  TICKET TO ANALYST';
        EXECUTE IMMEDIATE 'GRANT SELECT ON  AIRLINES TO ANALYST';
        EXECUTE IMMEDIATE 'GRANT SELECT ON  SCHEDULE TO ANALYST';
        EXECUTE IMMEDIATE 'GRANT SELECT ON  TERMINAL TO ANALYST';
        EXECUTE IMMEDIATE 'GRANT SELECT ON  AIRPORT TO ANALYST';    
        EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO ANALYST';
        DBMS_OUTPUT.PUT_LINE('User ACCOUNTANT CREATED and assigned the necessary priviliges');
   ELSE
        DBMS_OUTPUT.PUT_LINE('User already exists');
   END IF;
END;
/
